<?php

if( function_exists('acf_add_local_field_group') ) {

    acf_add_local_field_group(array(
        'key' => 'group_6335b0638d7cc',
        'title' => 'Vacature-instellingen',
        'fields' => array(
            array(
                'key' => 'field_6335b2ac30ad8',
                'label' => 'Vacature tekst',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'aria-label' => '',
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_6335b5045eef8',
                'label' => '',
                'name' => 'vac_requirements',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'aria-label' => '',
                'default_value' => '',
                'translations' => 'translate',
                'tabs' => 'all',
                'toolbar' => 'basic',
                'media_upload' => 0,
                'delay' => 0,
            ),
            array(
                'key' => 'field_6335b2c230ad9',
                'label' => 'Salaris / Contract',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_6335b6beee724',
                'label' => 'Min. aantal uur',
                'name' => 'vac_min_hours',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'translations' => 'translate',
                'placeholder' => '',
                'prepend' => '',
                'append' => 'uur',
                'min' => 0,
                'max' => 168,
                'step' => 1,
            ),
            array(
                'key' => 'field_6335b6ccee725',
                'label' => 'Max. aantal uur',
                'name' => 'vac_max_hours',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'translations' => 'translate',
                'placeholder' => '',
                'prepend' => '',
                'append' => 'uur',
                'min' => 0,
                'max' => 168,
                'step' => 1,
            ),
            array(
                'key' => 'field_6335b5ca73fe4',
                'label' => 'Dienstverband',
                'name' => 'vac_employment_type_code',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'fulltime' => 'Voltijd',
                    'parttime' => 'Deeltijd',
                    'fulltime_fixed_term' => 'Voltijd (Tijdelijk)',
                    'parttime_fixed_term' => 'Deeltijd (Tijdelijk)',
                    'internship' => 'Stage',
                    'freelance' => 'Freelance',
                ),
                'default_value' => false,
                'allow_null' => 1,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => 'Selecteer dienstverband',
            ),
            array(
                'key' => 'field_63f771170a5b0',
                'label' => 'Remote',
                'name' => 'vac_remote',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'no' => 'Nee',
                    'yes' => 'Ja',
                    'hybrid' => 'Hybride',
                ),
                'default_value' => 'no',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_63f7871e4068d',
                'label' => 'Salaris (valuta)',
                'name' => 'vac_currency_salary',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'EUR' => '€ (EUR)',
                    'USD' => '$ (USD)',
                    'GBP' => '£ (GBP)',
                ),
                'default_value' => 'EUR',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_63f787364068e',
                'label' => 'Min. salaris',
                'name' => 'vac_min_salary',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 0,
                'max' => '',
                'step' => 100,
            ),
            array(
                'key' => 'field_63f787664068f',
                'label' => 'Max. salaris',
                'name' => 'vac_max_salary',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 0,
                'max' => '',
                'step' => 100,
            ),
            array(
                'key' => 'field_63f7877740690',
                'label' => 'Salaris (periode)',
                'name' => 'vac_period',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'hour' => 'Per uur',
                    'day' => 'Per dag',
                    'week' => 'Per week',
                    'month' => 'Per maand',
                    'year' => 'Per jaar',
                ),
                'default_value' => 'month',
                'allow_null' => 1,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => 'Selecteer periode',
            ),
            array(
                'key' => 'field_64524814c4439',
                'label' => 'Specificaties',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_6335b0642e729',
                'label' => 'Ervaring',
                'name' => 'vac_experience_code',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'entry_level' => 'Starter',
                    'mid_level' => 'Medior',
                    'experienced' => 'Senior',
                    'student_school' => 'Student/Stagiair',
                ),
                'default_value' => false,
                'allow_null' => 1,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => 'Selecteer ervaringsniveau',
            ),
            array(
                'key' => 'field_6335b5a073fe1',
                'label' => 'Opleidingsniveau',
                'name' => 'vac_education_code',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'vmbo' => 'VMBO',
                    'mbo' => 'MBO',
                    'havo_vwo' => 'HAVO/VWO',
                    'bachelor_degree' => 'HBO Bachelor',
                    'master_degree' => 'WO Master',
                    'vocational' => 'Beroepsopleiding',
                ),
                'default_value' => false,
                'allow_null' => 1,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => 'Selecteer opleidingsniveau',
            ),
            array(
                'key' => 'field_64524de46c2f2',
                'label' => 'Bedrijf',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_6335b5af73fe2',
                'label' => 'Bedrijfsnaam',
                'name' => 'vac_company_name',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Bijv. Dutch Crowd Security',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6335b5c073fe3',
                'label' => 'Categorie',
                'name' => 'vac_category_code',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'security' => 'Beveiliging',
                ),
                'default_value' => 'security',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_63f7714800dfe',
                'label' => 'Locatie',
                'name' => 'vac_location',
                'type' => 'text',
                'instructions' => 'Wordt automatisch gegenereerd uit Plaatsnaam, Provincie en Land',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'readonly' => 1,
            ),
            array(
                'key' => 'field_6335b693ff087',
                'label' => 'Postcode',
                'name' => 'vac_zip_code',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '15',
                    'class' => '',
                    'id' => '',
                ),
                'aria-label' => '',
                'default_value' => '',
                'placeholder' => '1234 AB',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_63f76630b28b5',
                'label' => 'Plaatsnaam',
                'name' => 'vac_city',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'aria-label' => '',
                'default_value' => '',
                'placeholder' => 'Amsterdam',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_63f766918c993',
                'label' => 'Provincie',
                'name' => 'vac_state_name',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'Drenthe' => 'Drenthe',
                    'Flevoland' => 'Flevoland',
                    'Friesland' => 'Friesland',
                    'Gelderland' => 'Gelderland',
                    'Groningen' => 'Groningen',
                    'Limburg' => 'Limburg',
                    'Noord-Brabant' => 'Noord-Brabant',
                    'Noord-Holland' => 'Noord-Holland',
                    'Overijssel' => 'Overijssel',
                    'Utrecht' => 'Utrecht',
                    'Zeeland' => 'Zeeland',
                    'Zuid-Holland' => 'Zuid-Holland',
                ),
                'default_value' => false,
                'allow_null' => 1,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => 'Selecteer provincie',
            ),
            array(
                'key' => 'field_63f76640b28b6',
                'label' => 'Land',
                'name' => 'vac_country',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'aria-label' => '',
                'default_value' => '',
                'translations' => 'translate',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'readonly' => 1,
            ),
            array(
                'key' => 'field_63f76b8eff738',
                'label' => 'Landcode',
                'name' => 'vac_country_code',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '15',
                    'class' => '',
                    'id' => '',
                ),
                'aria-label' => '',
                'default_value' => '',
                'translations' => 'translate',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'readonly' => 1,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'vacancy',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => 'CPT - Vacancy',
        'show_in_rest' => 0,
    ));
    
}